version: '3'
services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-catelog-app
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/home/node/app
